//go:build !ignore_autogenerated

/*
Copyright 2026 The Korion Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	"k8s.io/api/core/v1"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AgentFeatures) DeepCopyInto(out *AgentFeatures) {
	*out = *in
	if in.AlertEnrichment != nil {
		in, out := &in.AlertEnrichment, &out.AlertEnrichment
		*out = new(AlertEnrichmentFeature)
		(*in).DeepCopyInto(*out)
	}
	if in.HealthAdvisor != nil {
		in, out := &in.HealthAdvisor, &out.HealthAdvisor
		*out = new(HealthAdvisorFeature)
		**out = **in
	}
	if in.SREDiagnostics != nil {
		in, out := &in.SREDiagnostics, &out.SREDiagnostics
		*out = new(SREDiagnosticsFeature)
		**out = **in
	}
	if in.CanaryDecision != nil {
		in, out := &in.CanaryDecision, &out.CanaryDecision
		*out = new(CanaryDecisionFeature)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AgentFeatures.
func (in *AgentFeatures) DeepCopy() *AgentFeatures {
	if in == nil {
		return nil
	}
	out := new(AgentFeatures)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AlertEnrichmentFeature) DeepCopyInto(out *AlertEnrichmentFeature) {
	*out = *in
	if in.SlackWebhookSecretRef != nil {
		in, out := &in.SlackWebhookSecretRef, &out.SlackWebhookSecretRef
		*out = new(v1.SecretKeySelector)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AlertEnrichmentFeature.
func (in *AlertEnrichmentFeature) DeepCopy() *AlertEnrichmentFeature {
	if in == nil {
		return nil
	}
	out := new(AlertEnrichmentFeature)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CanaryDecisionFeature) DeepCopyInto(out *CanaryDecisionFeature) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CanaryDecisionFeature.
func (in *CanaryDecisionFeature) DeepCopy() *CanaryDecisionFeature {
	if in == nil {
		return nil
	}
	out := new(CanaryDecisionFeature)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GitHubToolConfig) DeepCopyInto(out *GitHubToolConfig) {
	*out = *in
	if in.TokenSecretRef != nil {
		in, out := &in.TokenSecretRef, &out.TokenSecretRef
		*out = new(v1.SecretKeySelector)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GitHubToolConfig.
func (in *GitHubToolConfig) DeepCopy() *GitHubToolConfig {
	if in == nil {
		return nil
	}
	out := new(GitHubToolConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HealthAdvisorFeature) DeepCopyInto(out *HealthAdvisorFeature) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HealthAdvisorFeature.
func (in *HealthAdvisorFeature) DeepCopy() *HealthAdvisorFeature {
	if in == nil {
		return nil
	}
	out := new(HealthAdvisorFeature)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LLMProvider) DeepCopyInto(out *LLMProvider) {
	*out = *in
	if in.APIKeySecretRef != nil {
		in, out := &in.APIKeySecretRef, &out.APIKeySecretRef
		*out = new(v1.SecretKeySelector)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LLMProvider.
func (in *LLMProvider) DeepCopy() *LLMProvider {
	if in == nil {
		return nil
	}
	out := new(LLMProvider)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PlatformAgent) DeepCopyInto(out *PlatformAgent) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PlatformAgent.
func (in *PlatformAgent) DeepCopy() *PlatformAgent {
	if in == nil {
		return nil
	}
	out := new(PlatformAgent)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *PlatformAgent) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PlatformAgentList) DeepCopyInto(out *PlatformAgentList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]PlatformAgent, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PlatformAgentList.
func (in *PlatformAgentList) DeepCopy() *PlatformAgentList {
	if in == nil {
		return nil
	}
	out := new(PlatformAgentList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *PlatformAgentList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PlatformAgentSpec) DeepCopyInto(out *PlatformAgentSpec) {
	*out = *in
	in.LLMProvider.DeepCopyInto(&out.LLMProvider)
	in.Features.DeepCopyInto(&out.Features)
	if in.Runbooks != nil {
		in, out := &in.Runbooks, &out.Runbooks
		*out = make([]Runbook, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PlatformAgentSpec.
func (in *PlatformAgentSpec) DeepCopy() *PlatformAgentSpec {
	if in == nil {
		return nil
	}
	out := new(PlatformAgentSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PlatformAgentStatus) DeepCopyInto(out *PlatformAgentStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]metav1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.LastReconcileTime != nil {
		in, out := &in.LastReconcileTime, &out.LastReconcileTime
		*out = (*in).DeepCopy()
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PlatformAgentStatus.
func (in *PlatformAgentStatus) DeepCopy() *PlatformAgentStatus {
	if in == nil {
		return nil
	}
	out := new(PlatformAgentStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PlatformMap) DeepCopyInto(out *PlatformMap) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PlatformMap.
func (in *PlatformMap) DeepCopy() *PlatformMap {
	if in == nil {
		return nil
	}
	out := new(PlatformMap)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *PlatformMap) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PlatformMapList) DeepCopyInto(out *PlatformMapList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]PlatformMap, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PlatformMapList.
func (in *PlatformMapList) DeepCopy() *PlatformMapList {
	if in == nil {
		return nil
	}
	out := new(PlatformMapList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *PlatformMapList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PlatformMapSpec) DeepCopyInto(out *PlatformMapSpec) {
	*out = *in
	in.Tools.DeepCopyInto(&out.Tools)
	out.RefreshInterval = in.RefreshInterval
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PlatformMapSpec.
func (in *PlatformMapSpec) DeepCopy() *PlatformMapSpec {
	if in == nil {
		return nil
	}
	out := new(PlatformMapSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PlatformMapStatus) DeepCopyInto(out *PlatformMapStatus) {
	*out = *in
	if in.Topology != nil {
		in, out := &in.Topology, &out.Topology
		*out = new(runtime.RawExtension)
		(*in).DeepCopyInto(*out)
	}
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]metav1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.LastDiscoveryTime != nil {
		in, out := &in.LastDiscoveryTime, &out.LastDiscoveryTime
		*out = (*in).DeepCopy()
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PlatformMapStatus.
func (in *PlatformMapStatus) DeepCopy() *PlatformMapStatus {
	if in == nil {
		return nil
	}
	out := new(PlatformMapStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Runbook) DeepCopyInto(out *Runbook) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Runbook.
func (in *Runbook) DeepCopy() *Runbook {
	if in == nil {
		return nil
	}
	out := new(Runbook)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SREDiagnosticsFeature) DeepCopyInto(out *SREDiagnosticsFeature) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SREDiagnosticsFeature.
func (in *SREDiagnosticsFeature) DeepCopy() *SREDiagnosticsFeature {
	if in == nil {
		return nil
	}
	out := new(SREDiagnosticsFeature)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ToolConfig) DeepCopyInto(out *ToolConfig) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ToolConfig.
func (in *ToolConfig) DeepCopy() *ToolConfig {
	if in == nil {
		return nil
	}
	out := new(ToolConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ToolsConfig) DeepCopyInto(out *ToolsConfig) {
	*out = *in
	if in.ArgoCD != nil {
		in, out := &in.ArgoCD, &out.ArgoCD
		*out = new(ToolConfig)
		**out = **in
	}
	if in.Kiali != nil {
		in, out := &in.Kiali, &out.Kiali
		*out = new(ToolConfig)
		**out = **in
	}
	if in.Istio != nil {
		in, out := &in.Istio, &out.Istio
		*out = new(ToolConfig)
		**out = **in
	}
	if in.Kyverno != nil {
		in, out := &in.Kyverno, &out.Kyverno
		*out = new(ToolConfig)
		**out = **in
	}
	if in.Prometheus != nil {
		in, out := &in.Prometheus, &out.Prometheus
		*out = new(ToolConfig)
		**out = **in
	}
	if in.Loki != nil {
		in, out := &in.Loki, &out.Loki
		*out = new(ToolConfig)
		**out = **in
	}
	if in.GitHub != nil {
		in, out := &in.GitHub, &out.GitHub
		*out = new(GitHubToolConfig)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ToolsConfig.
func (in *ToolsConfig) DeepCopy() *ToolsConfig {
	if in == nil {
		return nil
	}
	out := new(ToolsConfig)
	in.DeepCopyInto(out)
	return out
}
